spring:
  profiles:
    active:
      - local
  output:
    ansi:
      enabled: ALWAYS

  # Program Arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job을 실행시킨다.
  batch:
    job:
      names: ${job.name:NONE} # job.name이 있으면 job.name의 값을 할당하고, 없으면 NONE을 할당한다. (NONE은 어떠한 배치도 실행하지 않겠다는 의미)
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: com.h2.Driver
---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/springbatch
    username: npcdja
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true